

#libraries ----
library(dplyr)
#library(tidyr)
#library(purrr)
library(stringr)
library(lubridate)
#library(readr)
#library(forcats)

#library(labelled)
#library(data.table)
#library(DT)
library(plotly)
#library(openxlsx)

library(shiny)
library(shinymanager)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(shinycssloaders)
library(fresh)
#library(shinya11y)

#library(phsstyles)
#library(phsmethods)

#all functions used in dashboard
source("functions.R")

#credentials for login
credentials <- readRDS("admin/credentials.rds")


#reference lists ----
#list of health boards
HBnames <- c("NHS Ayrshire & Arran", "NHS Borders", "NHS Dumfries & Galloway",
             "NHS Fife", "NHS Forth Valley", "NHS Grampian", "NHS Greater Glasgow & Clyde",
             "NHS Highland", "NHS Lanarkshire", "NHS Lothian", "NHS Tayside", "NHS Orkney",
             "NHS Shetland", "NHS Western Isles")

#list of council areas
CAnames <- c("Aberdeen City", "Aberdeenshire", "Angus", "Argyll and Bute", "City of Edinburgh", 
             "Clackmannanshire", "Dumfries and Galloway", "Dundee City", "East Ayrshire", 
             "East Dunbartonshire", "East Lothian", "East Renfrewshire", "Falkirk",
             "Fife", "Glasgow City", "Highland", "Inverclyde", "Midlothian", "Moray", 
             "Na h-Eileanan Siar", "North Ayrshire", "North Lanarkshire", "Orkney Islands", 
             "Perth and Kinross", "Renfrewshire", "Scottish Borders", "Shetland Islands", 
             "South Ayrshire", "South Lanarkshire", "Stirling", "West Dunbartonshire", 
             "West Lothian")

#list of developmental domains
domains <- c("Speech, language & communication", "Problem solving", "Gross motor",
             "Personal/Social", "Fine motor", "Emotional/Behavioural", 
             "Vision", "Hearing")


#sets colours for each line that appears in the dashboard
line_colours <- c("#3F3685", #phs-purple
                  "#9B4393", #phs-magenta
                  "#9B4393", #phs-magenta
                  "#1E7F84", #phs-teal
                  "#C73918", #phs-rust
                  "#D26146", #phs-rust-80
                  "#D26146", #phs-rust-80
                  
                  "#3F3685", #phs-purple
                  "#9B4393", #phs-magenta
                  "#0078D4", #phs-blue
                  "#83BB26", #phs-green
                  "#948DA3", #phs-graphite
                  "#1E7F84", #phs-teal
                  "#6B5C85", #phs-liberty
                  "#C73918", #phs-rust
                  
                  "#C73918", #phs-rust
                  "#9B4393", #phs-magenta
                  "#3F3685", #phs-purple
                  "#0078D4", #phs-blue
                  "#83BB26" #phs-green
) |>
  #name each of the elements after variables in plots so plots can refer to these names
  setNames(c("Ever breastfed", 
             "Reviews with 1 or more developmental concerns",
             "Overall breastfed",
             "Exclusively breastfed",
             "Reviews",
             "Valid reviews",
             "Meaningful reviews",
             domains,
             as.character(1:5)
  ))

#list of symbols to use in domains graph, as the default only assigns 6 symbols
domain_symbols <- c("circle", "triangle-down", "square", "diamond", "square-open", "cross", "x", "hourglass") |>
  setNames(domains)


#used to read in data and make options for selection
feeding_data_options <- c("firstvisit", "6-8 week")
development_data_options <- c("13-15m", "27-30m", "4-5y")



#read in data files ----
#six data files for the six types of graphs produced
#generated by the script ../read_in_data.R
load("data/heys_data.Rdata")





#mytheme ----
#must create a custom theme to make the colours on dashboard match PHS colours
mytheme <- create_theme(
  adminlte_color(
    light_blue = "#9B4393" # header bar = PHS-magenta
  ),
  adminlte_sidebar( # sidebar colours
    width = "290px",
    dark_bg = "#9B4393", # background colour (not selected) = PHS-magenta
    dark_hover_bg = "#3F3685", # background colour (when hovering) = PHS-purple
    dark_color = "#FFFFFF", # text colour (not selected) = white
    dark_hover_color = "#FFFFFF", #hover colour = white
    dark_submenu_bg = "#1E7F84", #sub-menu background colour = PHS-magenta-80
    dark_submenu_color = "#FFFFFF" #sub-menu text color = white
  ),
  adminlte_global(
    content_bg = "#FFF",
    box_bg = "#FFF",
    info_box_bg = "#FFF"
  )
  #adminlte_vars(
  #box_border_color = "#FFF"
  #)
)
